from typing import Protocol, runtime_checkable


@runtime_checkable
class IObjectStorage(Protocol):
    async def put_object(self, path: str, content: bytes, content_type: str) -> None: ...

    async def get_object(self, path: str) -> bytes: ...

    async def exists(self, path: str) -> bool: ...

    async def list_objects(self, prefix: str) -> list[str]: ...

    async def generate_upload_url(self, path: str) -> str: ...
