from enum import StrEnum


class DocumentStatus(StrEnum):
    PENDING_UPLOAD = "PENDING_UPLOAD"
    UPLOADED = "UPLOADED"
    PARSED = "PARSED"
    CHUNKED = "CHUNKED"
    GRAPH_EXTRACTED = "GRAPH_EXTRACTED"
    INDEXED = "INDEXED"
    FAILED = "FAILED"
    DELETED = "DELETED"
